/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.sanamed.view;

import ec.edu.espe.sanamed.controller.ProductsController;
import ec.edu.espe.sanamed.core.View;
import ec.edu.espe.sanamed.model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class AddProductView extends View {
    private ProductsController controller;
    
    /**
     * Creates new form AddProductView
     */
    public AddProductView(ProductsController controller) {
        this.controller = controller;
        initComponents();
    }
    
    @Override
    public void onReveal() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        ftxtPrice = new javax.swing.JFormattedTextField();
        btnAdd = new javax.swing.JButton();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("Agregar producto");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("ID:");

        jLabel5.setText("Descripcion:");

        txtaDescription.setColumns(20);
        txtaDescription.setRows(5);
        jScrollPane1.setViewportView(txtaDescription);

        jLabel6.setText("Precio:");

        ftxtPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtType)
                    .addComponent(txtName)
                    .addComponent(txtId)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ftxtPrice)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String id = txtId.getText().trim();
        String name = txtName.getText().trim();
        String type = txtType.getText().trim();
        String description = txtaDescription.getText().trim();
        String priceText = ftxtPrice.getText().trim();
        double price;
        
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo id es necesario");
            return;
        }
        
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo nombre es necesario");
            return;
        }
        
        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo tipo es necesario");
            return;
        }
        
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo descripcion es necesario");
            return;
        }
        
        if (priceText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo precio es necesario");
            return;
        }
        
        try {
            price = Double.parseDouble(priceText.replace(',', '.'));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El campo precio debe ser numerico");
            return;
        }
        
        controller.addProduct(new Product(id, name, description, type, price), (inserted, error) -> {
            if (inserted) {
                txtId.setText("");
                txtName.setText("");
                txtType.setText("");
                txtaDescription.setText("");
                ftxtPrice.setText("");
                JOptionPane.showMessageDialog(null, "Producto agregado con exito");
            } else {
                JOptionPane.showMessageDialog(null, error);
            }
        });
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JFormattedTextField ftxtPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextArea txtaDescription;
    // End of variables declaration//GEN-END:variables
}
