/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.sanamed.view;

import ec.edu.espe.sanamed.controller.UsersController;
import ec.edu.espe.sanamed.core.View;
import ec.edu.espe.sanamed.model.User;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class AddUserView extends View {
    private UsersController controller;
    
    /**
     * Creates new form AddUserView
     */
    public AddUserView(UsersController controller) {
        this.controller = controller;
        initComponents();
    }

    @Override
    public void onReveal() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("Agregar usuario");

        jLabel2.setText("Nombre de usuario:");

        jLabel3.setText("Email:");

        jLabel4.setText("Contraseña:");

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Confirmar contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addComponent(txtEmail)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addComponent(txtPassword)
                    .addComponent(txtPassword2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String username = txtUsername.getText().trim();
        String email = txtEmail.getText().trim();
        String password = String.copyValueOf(txtPassword.getPassword());
        String password2 = String.copyValueOf(txtPassword2.getPassword());
        
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario es requerido");
            return;
        }
        
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El email es requerido");
            return;
        }
        
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "La contraseña es requerido");
            return;
        }
        
        if (password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes confirmar la contraseña");
            return;
        }
        
        if (username.length() < 4 || username.length() > 24) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario debe estar entre 4 y 24 caracteres");
            return;
        }
        
        if (!username.matches("^[a-zA-Z0-9-_]+$")) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario solo puede contener: numeros, letras y guiones");
            return;
        }
        
        Pattern emailRegex = Pattern.compile(
            "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
        
        if (!emailRegex.matcher(email).find()) {
            JOptionPane.showMessageDialog(null, "El email es incorrecto");
            return;
        }
        
        if (password.length() < 4) {
            JOptionPane.showMessageDialog(null, "La contraseña debe tener minimo 4 caracteres");
            return;
        }
        
        if (!password.equals(password2)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            return;
        }
        
        controller.addUser(new User(username, email, password), (added, error) -> {
            if (!added) {
                JOptionPane.showMessageDialog(null, error);
                txtUsername.setText("");
                txtEmail.setText("");
                txtPassword.setText("");
                txtPassword2.setText("");
            } else {
             JOptionPane.showMessageDialog(null, "Usuario agregado con exito");   
            }
        });
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
